### ISSUE TITLE
I'm getting this error message

### ISSUE THREAD

**Issue by snoock** [yousefissa/Twitter-Follow-and-Unfollow-Bot#11]
Enter the number of the action that you want to take: 3
Do you want to keep going? Enter yes or no. 
yes

Traceback (most recent call last):
  File "D:\tweet\twitterBot.py", line 344, in <module>
    main_menu()
  File "D:\tweet\twitterBot.py", line 67, in main_menu
    Continue()
  File "D:\tweet\twitterBot.py", line 328, in Continue
    keep_going = input('Do you want to keep going? Enter yes or no. \n'
  File "<string>", line 1, in <module>
NameError: name 'yes' is not defined
>>> 
sorry I'm a noob

**Comment by axeforeverjumo** [comment]
Yes, the problem is your are inserting to a String variable this:
`continue = yes`
You have to make it like this:
`continue = 'yes'`
for that not write 
> yes

Write on the terminal

> 'yes'

And its going to work perfect.

**Comment by Wrexen** [comment]
Getting the same error. Even if i type 'yes' the bot will restart at the main menu.
Someone please can help ?

Greeting

**Comment by brahmanggi** [comment]
bump

**Comment by SPIRY-RO** [comment]
Same
